[workspace]

members = ["kv", "kv/bench", "db", "db/bench", "cli"]

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/arronzhang/nostr-db"
repository = "https://github.com/arronzhang/nostr-db.git"
authors = ["Arron zhang <arronzhang@me.com>"]